# Generated by Django 6.0.1 on 2026-01-08 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InternshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_source', models.CharField(choices=[('student_selected', 'Student selected from list'), ('student_proposed', 'Student proposed new company'), ('university_assigned', 'University assigned')], max_length=30)),
                ('proposed_company_name', models.CharField(blank=True, max_length=200)),
                ('proposed_company_district', models.CharField(blank=True, max_length=120)),
                ('proposed_company_address', models.CharField(blank=True, max_length=255)),
                ('proposed_company_contact', models.CharField(blank=True, max_length=200)),
                ('preferred_field', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='requests/cv/')),
                ('request_letter', models.FileField(blank=True, null=True, upload_to='requests/letters/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='placements.internshipperiod')),
                ('preferred_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='accounts.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'period')},
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('placement_letter', models.FileField(blank=True, null=True, upload_to='placements/letters/')),
                ('status', models.CharField(choices=[('pending_student_ack', 'Pending student acknowledgement'), ('active', 'Active'), ('on_hold', 'On hold'), ('completed', 'Completed'), ('terminated', 'Terminated')], default='pending_student_ack', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company')),
                ('industry_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.companycontact')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='placement', to='placements.internshiprequest')),
                ('university_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staffprofile')),
            ],
        ),
    ]
