# Generated by Django 6.0.1 on 2026-01-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshiprequest',
            name='acceptance_letter',
            field=models.FileField(blank=True, null=True, upload_to='requests/acceptance_letters/'),
        ),
        migrations.AddField(
            model_name='internshiprequest',
            name='acceptance_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internshiprequest',
            name='acceptance_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internshiprequest',
            name='acceptance_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internshiprequest',
            name='recommendation_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internshiprequest',
            name='recommendation_letter',
            field=models.FileField(blank=True, null=True, upload_to='requests/recommendation_letters/'),
        ),
        migrations.AlterField(
            model_name='internshiprequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('recommended', 'Recommendation issued'), ('acceptance_uploaded', 'Acceptance uploaded'), ('acceptance_verified', 'Acceptance verified'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
