# Generated by Django 6.0.1 on 2026-01-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0002_internshiprequest_acceptance_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshiprequest',
            name='coordinator_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='internshiprequest',
            name='coordinator_commented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internshiprequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('recommended', 'Recommendation issued'), ('acceptance_uploaded', 'Acceptance uploaded'), ('acceptance_verified', 'Acceptance verified'), ('rejected', 'Rejected'), ('returned_for_acceptance', 'Returned: Upload Acceptance Letter')], default='draft', max_length=40),
        ),
    ]
