# Generated by Django 6.0.1 on 2026-01-23 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0003_internshiprequest_coordinator_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='internshiprequest',
            name='recommendation_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internshiprequest',
            name='recommendation_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internshiprequest',
            name='recommendation_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_recommendation_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internshiprequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('recommendation_pending', 'Recommendation pending approval'), ('recommended', 'Recommendation issued'), ('acceptance_uploaded', 'Acceptance uploaded'), ('acceptance_verified', 'Acceptance verified'), ('rejected', 'Rejected'), ('returned_for_acceptance', 'Returned: Upload Acceptance Letter')], default='draft', max_length=40),
        ),
    ]
