# Generated by Django 6.0.1 on 2026-04-27 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0004_internshiprequest_recommendation_approved_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internshipperiod',
            options={'ordering': ['-is_active', '-start_date']},
        ),
    ]
