# Generated by Django 6.0.1 on 2026-04-27 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0005_alter_internshipperiod_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationLetterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default recommendation letter settings', max_length=120)),
                ('stamp_image', models.ImageField(blank=True, null=True, upload_to='recommendation_letter/stamps/')),
                ('signatory_name', models.CharField(blank=True, max_length=160)),
                ('signatory_title', models.CharField(blank=True, default='Dean', max_length=160)),
                ('signatory_email', models.EmailField(blank=True, max_length=254)),
                ('signatory_phone', models.CharField(blank=True, max_length=60)),
                ('footer_address', models.CharField(blank=True, default='Victoria Tower, Plot No. 1-13 Jinja Road P.O. Box 30866 Kampala, Uganda', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_recommendation_letter_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recommendation letter setting',
                'verbose_name_plural': 'Recommendation letter settings',
            },
        ),
    ]
