# Generated by Django 6.0.1 on 2026-04-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0006_recommendationlettersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationlettersettings',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='recommendation_letter/signatures/'),
        ),
    ]
