# Generated by Django 6.0.1 on 2026-01-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
