# Generated by Django 6.0.1 on 2026-01-29 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_staffprofile_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('role_university_supervisor', 'Role: University Supervisor'), ('role_industry_supervisor', 'Role: Industry Supervisor'), ('role_coordinator', 'Role: Coordinator')]},
        ),
    ]
