# Generated by Django 6.0.1 on 2026-01-29 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('role_university_supervisor', 'Role: VU_UniversitySupervisor'), ('role_industry_supervisor', 'Role: IndustrySupervisor'), ('role_coordinator', 'Role: VU_Coordinator')]},
        ),
    ]
