# Generated by Django 6.0.1 on 2026-06-19 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_passwordresetotp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('role_system_admin', 'Role: System Admin'), ('role_university_supervisor', 'Role: VU_UniversitySupervisor'), ('role_industry_supervisor', 'Role: IndustrySupervisor'), ('role_coordinator', 'Role: VU_Coordinator')]},
        ),
        migrations.CreateModel(
            name='AccountActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
