# Generated by Django 6.0.1 on 2026-01-08 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('placements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_no', models.PositiveIntegerField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('activities', models.TextField()),
                ('challenges', models.TextField(blank=True)),
                ('lessons', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tracking/weekly_logs/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('returned_for_edit', 'Returned for edit'), ('approved_by_company', 'Approved by company')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('company_action_at', models.DateTimeField(blank=True, null=True)),
                ('return_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_log_actions', to=settings.AUTH_USER_MODEL)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_logs', to='placements.placement')),
            ],
            options={
                'ordering': ['-from_date'],
                'unique_together': {('placement', 'week_no')},
            },
        ),
    ]
