# Generated by Django 6.0.1 on 2026-01-08 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_industrysupervisorprofile'),
        ('placements', '0001_initial'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('findings', models.TextField()),
                ('recommendations', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tracking/site_visits/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_visits', to='placements.placement')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.staffprofile')),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
    ]
