# Generated by Django 6.0.1 on 2026-01-10 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_sitevisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday')], max_length=3)),
                ('work_assignment', models.TextField(blank=True)),
                ('activities_steps', models.TextField(blank=True)),
                ('weekly_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tracking.weeklylog')),
            ],
            options={
                'ordering': ['day'],
                'unique_together': {('weekly_log', 'day')},
            },
        ),
    ]
