# Generated by Django 6.0.1 on 2026-01-11 02:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('placements', '0003_internshiprequest_coordinator_comment_and_more'),
        ('tracking', '0003_weeklylogentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_work_expectations', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('knowledge_and_learning', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ethical_awareness', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('interpersonal_relations', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication_skills', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('attendance', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('punctuality', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('flexibility', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('dependability', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('culture_fit', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('dress_code', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('behaviour', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('work_productivity', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('basic_work_expectations_comment', models.TextField(blank=True)),
                ('knowledge_and_learning_comment', models.TextField(blank=True)),
                ('ethical_awareness_comment', models.TextField(blank=True)),
                ('interpersonal_relations_comment', models.TextField(blank=True)),
                ('communication_skills_comment', models.TextField(blank=True)),
                ('attendance_comment', models.TextField(blank=True)),
                ('punctuality_comment', models.TextField(blank=True)),
                ('flexibility_comment', models.TextField(blank=True)),
                ('dependability_comment', models.TextField(blank=True)),
                ('culture_fit_comment', models.TextField(blank=True)),
                ('dress_code_comment', models.TextField(blank=True)),
                ('behaviour_comment', models.TextField(blank=True)),
                ('work_productivity_comment', models.TextField(blank=True)),
                ('recommend_employment', models.BooleanField(blank=True, null=True)),
                ('recommend_comment', models.TextField(blank=True)),
                ('other_comments', models.TextField(blank=True)),
                ('supervisor_name', models.CharField(blank=True, max_length=120)),
                ('supervisor_signature', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='industry_evaluations', to='companies.company')),
                ('placement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='industry_evaluation', to='placements.placement')),
                ('supervisor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industry_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
