# Generated by Django 6.0.1 on 2026-01-13 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0003_internshiprequest_coordinator_comment_and_more'),
        ('tracking', '0004_industryevaluation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('understanding_of_internship', models.PositiveSmallIntegerField(default=0)),
                ('support_framework', models.PositiveSmallIntegerField(default=0)),
                ('culture_fit', models.PositiveSmallIntegerField(default=0)),
                ('work_output', models.PositiveSmallIntegerField(default=0)),
                ('general_presentation', models.PositiveSmallIntegerField(default=0)),
                ('understanding_of_internship_comment', models.TextField(blank=True, default='')),
                ('support_framework_comment', models.TextField(blank=True, default='')),
                ('culture_fit_comment', models.TextField(blank=True, default='')),
                ('work_output_comment', models.TextField(blank=True, default='')),
                ('general_presentation_comment', models.TextField(blank=True, default='')),
                ('recommendation', models.TextField(blank=True, default='')),
                ('supervisor_name', models.CharField(blank=True, default='', max_length=255)),
                ('supervisor_signature', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_evaluation', to='placements.placement')),
                ('supervisor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
