# Generated by Django 6.0.1 on 2026-01-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_supervisorresultsreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorresultsreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
