# Generated by Django 6.0.1 on 2026-01-18 09:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0003_internshiprequest_coordinator_comment_and_more'),
        ('tracking', '0007_supervisorresultsreport_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(blank=True, max_length=200)),
                ('internship_site', models.CharField(blank=True, max_length=200)),
                ('eval_date', models.DateField(default=django.utils.timezone.localdate)),
                ('q1', models.TextField(blank=True)),
                ('q2', models.TextField(blank=True)),
                ('q3', models.TextField(blank=True)),
                ('q4', models.TextField(blank=True)),
                ('q5', models.TextField(blank=True)),
                ('q6', models.TextField(blank=True)),
                ('q7', models.TextField(blank=True)),
                ('q8', models.TextField(blank=True)),
                ('q9', models.TextField(blank=True)),
                ('q10', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_evaluation', to='placements.placement')),
                ('student_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
