# Generated by Django 6.0.1 on 2026-01-26 14:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_staffprofile_phone'),
        ('tracking', '0008_studentevaluation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitevisit',
            options={'ordering': ['-scheduled_at']},
        ),
        migrations.AlterModelOptions(
            name='weeklylogentry',
            options={},
        ),
        migrations.RenameField(
            model_name='sitevisit',
            old_name='recommendations',
            new_name='agenda',
        ),
        migrations.RemoveField(
            model_name='sitevisit',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='sitevisit',
            name='findings',
        ),
        migrations.RemoveField(
            model_name='sitevisit',
            name='visit_date',
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='actual_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='meeting_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='scheduled_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=12),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='visit_type',
            field=models.CharField(choices=[('physical', 'Physical'), ('zoom', 'Virtual (Zoom)'), ('gmeet', 'Virtual (Google Meet)'), ('other', 'Virtual (Other)')], default=django.utils.timezone.now, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_visits', to='accounts.staffprofile'),
        ),
        migrations.CreateModel(
            name='SiteVisitAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('site_visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ack', to='tracking.sitevisit')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SiteVisitReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('progress', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('student_attended', models.BooleanField(default=True)),
                ('industry_supervisor_present', models.BooleanField(default=False)),
                ('assessment', models.CharField(choices=[('satisfactory', 'Satisfactory'), ('needs_improvement', 'Needs improvement')], default='satisfactory', max_length=20)),
                ('attachment', models.FileField(blank=True, upload_to='site_visits/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('site_visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='tracking.sitevisit')),
            ],
        ),
    ]
