# Generated by Django 6.0.1 on 2026-02-01 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_alter_sitevisit_options_alter_weeklylogentry_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorresultsreport',
            name='coordinator_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supervisorresultsreport',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='supervisorresultsreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('needs_changes', 'Needs Changes'), ('resubmitted', 'Resubmitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='supervisorresultsreport',
            name='supervisor_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
