# Generated by Django 6.0.1 on 2026-04-30 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0012_industrysupervisorresultsreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyLogAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tracking/weekly_logs/attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('weekly_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tracking.weeklylog')),
            ],
            options={
                'ordering': ['uploaded_at', 'id'],
            },
        ),
    ]
