# Generated by Django 6.0.1 on 2026-04-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_weeklylogattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
    ]
