# Generated by Django 6.0.1 on 2026-06-19 18:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0007_recommendationlettersettings_signature_image'),
        ('tracking', '0014_notification_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInternshipReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to='tracking/student_reports/')),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('submitted', 'Submitted')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_internship_report', to='placements.placement')),
                ('student_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internship_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at', '-updated_at'],
            },
        ),
    ]
